Update README.md
ROKT/tag-release-buildkite-plugin pull request #1
Opened 2021-08-02 23:07 UTC by activehigh

Fix readme

2021-08-02 23:35 UTC, BEvgeniyS approved these changes

2021-08-02 23:35 UTC, AaronChelvan reviewed
Some typos - `releas`

2021-08-02 23:37 UTC, BrunoChauvet approved these changes

2021-08-02 23:38 UTC, BrunoChauvet requested changes
Typo in plugin name `tag-releas` missing the `e`

2021-08-03 00:03 UTC, BrunoChauvet approved these changes

2021-08-03 00:08 UTC, merged